kind: Deployment
apiVersion: apps/v1
metadata:
  name: hertzbeat
  namespace: hertzbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hertzbeat
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hertzbeat
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: hertzbeat-cm
            items:
              - key: application.yml
                path: application.yml
            defaultMode: 420
      containers:
        - name: hertzbeat
          image: 'quay.io/tancloud/hertzbeat:latest'
          ports:
            - containerPort: 1157
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: LANG
              value: en_US.UTF-8
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /opt/hertzbeat/config/application.yml
              subPath: application.yml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
